<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="E_View.aspx.cs" Inherits="NDSO.ndso.E_View" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title></title>
     <link rel="stylesheet" href="Hospital.css" type="text/css"/>
    <link rel="stylesheet" href="Admin.css" type="text/css"/>
</head>
<body>
    <form id="form1" runat="server">
     <div class="side">
    <div class="inside">
        
        
    </div>
        <h1>Tasks</h1>
        <ul class="menu_list">
        <li class="list"><a class="text" href="Admin.aspx">Add Medicine</a></li>
        <li class="list"><a class="text" href="E_View.aspx">Medicine details</a></li>
        <li class="list"><a class="text" href="ViewOrders.aspx">Available Orders</a></li>
        <li class="list"><a class="text" href="#">Details Update</a></li>
        </ul>
    </div>
        <div class="tops">
            <div class="in_top">
                <asp:Label ID="Namesi"  runat="server" CssClass="User"  ></asp:Label>
                <asp:Label ID="Sur"  runat="server" CssClass="User"  ></asp:Label>
            </div>
        </div>
        <div class="bottom">
            <center>
            <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" DataKeyNames="Medication_Code" DataSourceID="SqlDataSource1" EmptyDataText="There are no data records to display.">
                <Columns>
                    <asp:TemplateField HeaderText="User ID" SortExpression="Userid">
                        <EditItemTemplate>
                            <asp:TextBox ID="TextBox1" runat="server" Text='<%# Bind("Userid") %>'></asp:TextBox>
                        </EditItemTemplate>
                        <ItemTemplate>
                            <asp:Label ID="Label1" runat="server" Text='<%# Bind("Userid") %>'></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                    <asp:TemplateField HeaderText="Medication" SortExpression="Medication">
                        <EditItemTemplate>
                            <asp:TextBox ID="TextBox2" runat="server" Text='<%# Bind("Medication") %>'></asp:TextBox>
                        </EditItemTemplate>
                        <ItemTemplate>
                            <asp:Label ID="Label2" runat="server" Text='<%# Bind("Medication") %>'></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                    <asp:TemplateField HeaderText="Quantity" SortExpression="Quantity">
                        <EditItemTemplate>
                            <asp:TextBox ID="TextBox3" runat="server" Text='<%# Bind("Quantity") %>'></asp:TextBox>
                        </EditItemTemplate>
                        <ItemTemplate>
                            <asp:Label ID="Label3" runat="server" Text='<%# Bind("Quantity") %>'></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                    <asp:TemplateField HeaderText="Price" SortExpression="Price">
                        <EditItemTemplate>
                            <asp:TextBox ID="TextBox4" runat="server" Text='<%# Bind("Price") %>'></asp:TextBox>
                        </EditItemTemplate>
                        <ItemTemplate>
                            <asp:Label ID="Label4" runat="server" Text='<%# Bind("Price") %>'></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                    <asp:TemplateField HeaderText="Expiry Date" SortExpression="Expiry_Date">
                        <EditItemTemplate>
                            <asp:TextBox ID="TextBox5" runat="server" Text='<%# Bind("Expiry_Date") %>'></asp:TextBox>
                        </EditItemTemplate>
                        <ItemTemplate>
                            <asp:Label ID="Label5" runat="server" Text='<%# Bind("Expiry_Date") %>'></asp:Label>
                        </ItemTemplate>
                    </asp:TemplateField>
                    <asp:BoundField DataField="Medication_Code" HeaderText="Medication Code" ReadOnly="True" SortExpression="Medication_Code" />
                </Columns>
            </asp:GridView>
            <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:HealthConnectionString1 %>" DeleteCommand="DELETE FROM [Medications] WHERE [Medication_Code] = @Medication_Code" InsertCommand="INSERT INTO [Medications] ([Userid], [Medication], [Quantity], [Price], [Expiry_Date], [Medication_Code]) VALUES (@Userid, @Medication, @Quantity, @Price, @Expiry_Date, @Medication_Code)" SelectCommand="SELECT [Userid], [Medication], [Quantity], [Price], [Expiry_Date], [Medication_Code] FROM [Medications]" UpdateCommand="UPDATE [Medications] SET [Userid] = @Userid, [Medication] = @Medication, [Quantity] = @Quantity, [Price] = @Price, [Expiry_Date] = @Expiry_Date WHERE [Medication_Code] = @Medication_Code">
                <DeleteParameters>
                    <asp:Parameter Name="Medication_Code" Type="String" />
                </DeleteParameters>
                <InsertParameters>
                    <asp:Parameter Name="Userid" Type="String" />
                    <asp:Parameter Name="Medication" Type="String" />
                    <asp:Parameter Name="Quantity" Type="String" />
                    <asp:Parameter Name="Price" Type="String" />
                    <asp:Parameter Name="Expiry_Date" Type="String" />
                    <asp:Parameter Name="Medication_Code" Type="String" />
                </InsertParameters>
                <UpdateParameters>
                    <asp:Parameter Name="Userid" Type="String" />
                    <asp:Parameter Name="Medication" Type="String" />
                    <asp:Parameter Name="Quantity" Type="String" />
                    <asp:Parameter Name="Price" Type="String" />
                    <asp:Parameter Name="Expiry_Date" Type="String" />
                    <asp:Parameter Name="Medication_Code" Type="String" />
                </UpdateParameters>
            </asp:SqlDataSource>
            </center>
        </div>
       
    </form>
</body>
</html>
