<%@ Page Language="C#" AutoEventWireup="true" CodeBehind="UpdateOrder.aspx.cs" Inherits="NDSO.ndso.UpdateOrder" %>

<!DOCTYPE html>

<html xmlns="http://www.w3.org/1999/xhtml">
<head runat="server">
    <title>Updating Order</title>
    <link rel="stylesheet" href="Hospital.css" type="text/css"/>
</head>
<body>
    <form id="form1" runat="server">
   <div class="side">
    <div class="inside">
        
        
    </div>
        <h1>Tasks</h1>
        <ul class="menu_list">
        <li class="list"><a class="text" href="Hospital.aspx">Place Order</a></li>
        <li class="list"><a class="text" href="UpdateOrder.aspx">Made Order</a></li>
        <li class="list"><a class="text" href="#">Update Order</a></li>
        </ul>
    </div>
        <div class="tops">
            <div class="in_top">
                <asp:Label ID="Namesi"  runat="server" CssClass="labels"></asp:Label>
            </div>
        </div>
        <div class="bottom">
            <center>
            <asp:GridView ID="GridView1" runat="server" AutoGenerateColumns="False" AutoGenerateDeleteButton="True" AutoGenerateEditButton="True" DataSourceID="SqlDataSource1" DataKeyNames="Order_Number">
                <Columns>
                    <asp:BoundField DataField="Medication" HeaderText="Medication" SortExpression="Medication" />
                    <asp:BoundField DataField="Quantity" HeaderText="Quantity" SortExpression="Quantity" />
                    <asp:BoundField DataField="Medication_Cost" HeaderText="Medication_Cost" SortExpression="Medication_Cost" />
                    <asp:BoundField DataField="Distance" HeaderText="Distance" SortExpression="Distance" />
                    <asp:BoundField DataField="Delivery_Cost" HeaderText="Delivery_Cost" SortExpression="Delivery_Cost" />
                    <asp:BoundField DataField="Total_Cost" HeaderText="Total_Cost" SortExpression="Total_Cost" />
                    <asp:BoundField DataField="Status" HeaderText="Status" SortExpression="Status" />
                    <asp:BoundField DataField="Name" HeaderText="Name" SortExpression="Name" />
                    <asp:BoundField DataField="Order_Number" HeaderText="Order_Number" InsertVisible="False" ReadOnly="True" SortExpression="Order_Number" />
                </Columns>
            </asp:GridView>
            <asp:SqlDataSource ID="SqlDataSource1" runat="server" ConnectionString="<%$ ConnectionStrings:HealthConnectionString1 %>" SelectCommand="SELECT * FROM [Orders]" UpdateCommand="UPDATE Orders SET Medication=@Medication, Quantity=@Quantity,Medication_Cost=@Medication_Cost,Distance=@Distance,Delivery_Cost=@Delivery_Cost,Total_Cost=@Total_Cost WHERE Order_Number=@Order_Number "></asp:SqlDataSource>
            </center>
        </div>
    </form>
</body>
</html>
